### PR TITLE
Use FindMatlab module instead of mex.cmake

### PR DESCRIPTION
**Pull request by jamiesnape**
In response to RobotLocomotion/drake#3596.

PTAL @rdeits. Please double check that everything MATLAB/MOSEK-related works as expected as I only have limited access to licenses for those.

FYI @RussTedrake.

### CODE REVIEW

**Comment by rdeits** [comment]
I've mirrored this from my fork in #48 so that Travis will be allowed to use the Mosek license. I'll test the Matlab components on my machine.

**Comment by jamiesnape** [comment]
Thanks.

**Comment by rdeits** [comment]
This seems to be fine on Linux, but on my Mac I can no longer load the Mosek libraries:

```
± CTEST_OUTPUT_ON_FAILURE=1 make test                                        1 ↵  git:(use-find-matlab) 15:23:47
Running tests...
Test project /Users/rdeits/locomotion/iris-distro/pod-build/iris_project-prefix/src/iris_project-build
      Start  1: irisDemo
 1/13 Test  #1: irisDemo ............................***Exception: Other  0.54 sec
dyld: Library not loaded: @loader_path/libmosek64.7.1.dylib
  Referenced from: /Users/rdeits/locomotion/iris-distro/pod-build/iris_project-prefix/src/iris_project-build/bin/irisDemo
  Reason: image not found
```

**Comment by jamiesnape** [comment]
Which version of CMake are you using on Mac?

**Comment by jamiesnape** [comment]
Try removing this commit: https://github.com/rdeits/iris-distro/pull/47/commits/6b17425461fd93315eae818a72ae8efdb8655e36

**Comment by rdeits** [comment]
cmake 3.5.2

**Comment by rdeits** [comment]
I rebased out 6b17425 but got the same failures, I'm afraid.

**Comment by jamiesnape** [comment]
Strangely the testing that I was able to do was on a Mac. What is your workflow?
```
cd iris-distro
make
make test
```
?

**Comment by rdeits** [comment]
That's exactly what I'm doing as well. And now it seems that I'm getting the same failures even on master. I'm not sure what's going on with my system.

**Comment by rdeits** [comment]
I'm experimenting with setting up an OSX build on travis in order to get a reliable second opinion over at #48

**Comment by jamiesnape** [comment]
Cool, thanks.

**Comment by jamiesnape** [comment]
I added two small changes and started some builds of Drake using that version.

**Comment by rdeits** [comment]
Ok, thanks. I've rebased #48 to include the new commits, and I've very nearly finished jumping through all of the Travis OSX hoops.

**Comment by rdeits** [comment]
#48 is happy on linux and OSX now. If this works on OSX for you and it works in Drake then I'm OK with merging.

**Comment by jamiesnape** [comment]
Everything is good with drake and locally with me, so please merge #48.

**Pull request merged**
