### PR TITLE
Add basic Bazel build and CMake exported targets

### PR DESCRIPTION
**Pull request by jamiesnape**
PTAL @rdeits.

* To support Bazel, I had  to move the headers into a directory structure similar to that when they are installed, so they now reside in `iris/` subdirectories.
* I have a branch that builds MOSEK using Bazel, but it is not quite ready, so use `pkg-config` and the CMake MOSEK repository for now.
* Bazel builds are GCC-only on Linux and Clang-only on Mac for now.
* I need to add all the Python modules to the Bazel build to get the Python tests running, though that is non-trivial for Matplotlib.
* For CMake, tests will now run from the build tree if IRIS has been built but not installed.
* There are now exported targets for the C++ libraries, which should make them easier to integrate with other projects, if so desired.
* I also added support for (and tested with) the Intel and PGI compilers, as well as potentially other compilers supported by CMake 3.1 and above.
* By nature of using `pybind11`, I believe the minimum required CMake version was 2.8.12. That has been formalized and, hopefully, preserved.

### CODE REVIEW

**Comment by rdeits** [comment]
How much work would it be to add a bazel build to Travis?

**Comment by jamiesnape** [comment]
Not sure. I will look into it.

**Comment by rdeits** [comment]
@jamiesnape I assume this was all covered in #66 and friends, correct?

**Comment by jamiesnape** [comment]
Yes, thanks.

**Comment by jamiesnape** [comment]
Except the Bazel build. If you still want that, I can PR it separately.

**Pull request closed without merging**
